### PR TITLE
Add AMD SPI control registers

### PR DESCRIPTION
**Pull request by benbaker76**
Added some SPI control registers.

```
$ sudo python3 chipsec_util.py reg read SPI_Cntrl0

################################################################
##                                                            ##
##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
##                                                            ##
################################################################
[CHIPSEC] Version : 1.7.1
[CHIPSEC] OS      : Linux 5.14.0-custom #1 SMP Tue Aug 31 00:25:42 EDT 2021 x86_64
[CHIPSEC] Python  : 3.9.5 (64-bit)

****** Chipsec Linux Kernel module is licensed under GPL 2.0
[CHIPSEC] API mode: using CHIPSEC kernel module API
[!]       Unknown PCH: VID = 0x1022, DID = 0x790E, RID = 0xFF; Using Default.
[!]            Results from this system may be incorrect.
[CHIPSEC] Helper  : LinuxHelper (/home/***/Programming/chipsec/chipsec/helper/linux/chipsec.ko)
[CHIPSEC] Platform: Renoir Root Complex
[CHIPSEC]      VID: 1022
[CHIPSEC]      DID: 1630
[CHIPSEC]      RID: 00
[CHIPSEC] PCH     : Default PCH
[CHIPSEC]      VID: FFFF
[CHIPSEC]      DID: FFFF
[CHIPSEC]      RID: FF
[CHIPSEC] Executing command 'reg' with args ['read', 'SPI_Cntrl0']

[CHIPSEC] SPI_Cntrl0=0x4F0C2105
[*] SPI_Cntrl0 = 0x4F0C2105 << SPI_Cntrl0 Register (SPIBAR + 0x0)
    [00] SPI_OpCode       = 5 << When software uses the alternate program method to communicate with the SPI ROM, this register contains the OPCODE 
    [08] TxByteCount      = 1 << Number of bytes to be sent to SPI ROM 
    [12] RxByteCount      = 2 << Number of bytes to be received from the SPI ROM 
    [16] ExecuteOpCode    = 0 << Write 1 to execute the transaction in the alternate program registers. Write 0 has no effect. When the transaction is complete, this bit will return 0. If the command is an illegal command, the bit cannot be set and thereby cannot execute 
    [19] SpiArbEnable     = 1 << If a MAC is sharing the ROM with the SB, both chips will need to go through an arbitration process before either one can access the ROM. This bit enables the arbitration. If MAC is not sharing the SPI ROM, BIOS should set this bit to 0 to speed up the SPI ROM access 
    [20] FifoPtrClr       = 0 << (write only) A write of 1 to this bit will clear the internal FIFO pointer 
    [21] FifoPtrInc       = 0 << (write only ) A write of 1 to this bit will cause the internal FIFO pointer to be incremented by 1 
    [22] SpiAccessMacRomEn = 0 << This is a clear-once protection bit; once set, software cannot access MAC’s portion of the ROM space (lower 512KB). 
    [23] SpiHostAccessRomEn = 0 << This is a clear-once protection bit; once set, MAC cannot access BIOS ROM space (upper 512KB) 
    [24] ArbWaitCount     = 7 << Under ROM sharing mode (with the MAC) this defines the amount of wait time this controller will assert HOLD# before it should access the SPI ROM. This time is to allow the MAC to sample HOLD#. 
    [27] SpiBridgeDisable = 1 << Setting this bit will disable the SPI bridge mode (SB600 will act as a SPI-LPC bridge to the MAC) 
    [28] Reserved         = 4
```

### CODE REVIEW

**Comment by kerneis-anssi** [comment]
Thanks for the pull request. It looks like the reference you used is for SB600, an old southbridge architecture. renoir.xml is focused on family 17h models, which is documented in https://www.amd.com/system/files/TechDocs/55570-B1-PUB.zip. You'll see there that access modes have changed, and most of the fields documented for SB600 are now marked as reserved (and conversely, new fields have been introduced in reserved ranges). A few fields overlap though.

I'd be happy to integrate something based on this documentation if you want, but I may go ahead and implement it myself in the next couple of days anyway. Thanks for the pointers to BIOS locking, it confirms what I found in other docs.

We could put your XML in a separate sb600.xml configuration. I'm not sure we want to support such old architectures though—chipsec assumes a PCH for Intel processors (ie. no separate southbridge), which is the equivalent of FCH for AMD. You may find the following page useful, it's easy to get lost in AMD names: https://en.wikipedia.org/wiki/List_of_AMD_chipsets

**Comment by benbaker76** [comment]
Thanks for linking to the right document. If you plan on implementing this I'll just sit back and wait. Thanks again for your contribution.

One other thing could you please include the Guid and Size to the UEFI module output in access_uefispec.py? It was part of this pull request. It's useful information to help determine which modules in a BIOS have loaded.

**Comment by benbaker76** [comment]
My BIOS contains multiple modules for AmdSetup. Here's an example of the following command with the addition of Guid and Size:
```
$ sudo python3 chipsec_main.py -m chipsec.modules.common.uefi.access_uefispec | grep AmdSetup
[*] Variable AmdSetup (NV+BS+RT) Guid 3a997502-647a-4c82-998e-52ef9486a247 Size 0x5a8
```
CbsSetupDxeRN (Renoir):
`0x13689     VarStore: VarStoreId: 0x5000 [3A997502-647A-4C82-998E-52EF9486A247], Size: 0x5A8, Name: AmdSetup {24 1F 02 75 99 3A 7A 64 82 4C 99 8E 52 EF 94 86 A2 47 00 50 A8 05 41 6D 64 53 65 74 75 70 00}`

CbsSetupDxeRV (Raven Ridge):
`0x16BD9     VarStore: VarStoreId: 0x5000 [3A997502-647A-4C82-998E-52EF9486A247], Size: 0x5A7, Name: AmdSetup {24 1F 02 75 99 3A 7A 64 82 4C 99 8E 52 EF 94 86 A2 47 00 50 A7 05 41 6D 64 53 65 74 75 70 00}`
Based on the Size we can determine that the CbsSetupDxeRN module has loaded.

**Comment by kerneis-anssi** [comment]
I've just pushed a very complete extraction of AMD registers to the `amd` branch, please feel free to test and report how it works for you!

The change to access_uefispec.py does not really belong to this AMD work but it seems generally useful. Do you want to open a separate PR to upstream to get it merged yourself? Otherwise I'll probably suggest it myself whenever I have some time.

**Pull request closed without merging**
